on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

name: Release Package 🚀

jobs:
  check:
    name: Release (from ramnog)
    uses: hta-pharma/ramnog/.github/workflows/Release-package.yaml@main


  
